#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technologique_SVC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TechnologiqueDB1")]
	public partial class TechnologiqueLinq1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public TechnologiqueLinq1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TechnologiqueDB1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TechnologiqueLinq1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TechnologiqueLinq1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TechnologiqueLinq1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TechnologiqueLinq1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cart> Carts
		{
			get
			{
				return this.GetTable<Cart>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cart")]
	public partial class Cart
	{
		
		private int _User_Id;
		
		private System.Nullable<int> _Product_Id;
		
		private string _Paid;
		
		private System.Nullable<int> _Cart_Id;
		
		public Cart()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int NOT NULL")]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this._User_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Id", DbType="Int")]
		public System.Nullable<int> Product_Id
		{
			get
			{
				return this._Product_Id;
			}
			set
			{
				if ((this._Product_Id != value))
				{
					this._Product_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paid", DbType="NChar(10)")]
		public string Paid
		{
			get
			{
				return this._Paid;
			}
			set
			{
				if ((this._Paid != value))
				{
					this._Paid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cart_Id", DbType="Int")]
		public System.Nullable<int> Cart_Id
		{
			get
			{
				return this._Cart_Id;
			}
			set
			{
				if ((this._Cart_Id != value))
				{
					this._Cart_Id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Product_Id;
		
		private string _Prod_Name;
		
		private string _Prod_Description;
		
		private System.Nullable<int> _Prod_Stock;
		
		private System.Nullable<float> _Prod_Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduct_IdChanging(int value);
    partial void OnProduct_IdChanged();
    partial void OnProd_NameChanging(string value);
    partial void OnProd_NameChanged();
    partial void OnProd_DescriptionChanging(string value);
    partial void OnProd_DescriptionChanged();
    partial void OnProd_StockChanging(System.Nullable<int> value);
    partial void OnProd_StockChanged();
    partial void OnProd_PriceChanging(System.Nullable<float> value);
    partial void OnProd_PriceChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Product_Id
		{
			get
			{
				return this._Product_Id;
			}
			set
			{
				if ((this._Product_Id != value))
				{
					this.OnProduct_IdChanging(value);
					this.SendPropertyChanging();
					this._Product_Id = value;
					this.SendPropertyChanged("Product_Id");
					this.OnProduct_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Name", DbType="NVarChar(MAX)")]
		public string Prod_Name
		{
			get
			{
				return this._Prod_Name;
			}
			set
			{
				if ((this._Prod_Name != value))
				{
					this.OnProd_NameChanging(value);
					this.SendPropertyChanging();
					this._Prod_Name = value;
					this.SendPropertyChanged("Prod_Name");
					this.OnProd_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Description", DbType="NVarChar(MAX)")]
		public string Prod_Description
		{
			get
			{
				return this._Prod_Description;
			}
			set
			{
				if ((this._Prod_Description != value))
				{
					this.OnProd_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Prod_Description = value;
					this.SendPropertyChanged("Prod_Description");
					this.OnProd_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Stock", DbType="Int")]
		public System.Nullable<int> Prod_Stock
		{
			get
			{
				return this._Prod_Stock;
			}
			set
			{
				if ((this._Prod_Stock != value))
				{
					this.OnProd_StockChanging(value);
					this.SendPropertyChanging();
					this._Prod_Stock = value;
					this.SendPropertyChanged("Prod_Stock");
					this.OnProd_StockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Price", DbType="Real")]
		public System.Nullable<float> Prod_Price
		{
			get
			{
				return this._Prod_Price;
			}
			set
			{
				if ((this._Prod_Price != value))
				{
					this.OnProd_PriceChanging(value);
					this.SendPropertyChanging();
					this._Prod_Price = value;
					this.SendPropertyChanged("Prod_Price");
					this.OnProd_PriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Id;
		
		private string _U_Uname;
		
		private string _U_Pwd;
		
		private string _U_Email;
		
		private System.Nullable<int> _Address_Id;
		
		private System.Nullable<int> _Cart_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdChanging(int value);
    partial void OnUser_IdChanged();
    partial void OnU_UnameChanging(string value);
    partial void OnU_UnameChanged();
    partial void OnU_PwdChanging(string value);
    partial void OnU_PwdChanged();
    partial void OnU_EmailChanging(string value);
    partial void OnU_EmailChanged();
    partial void OnAddress_IdChanging(System.Nullable<int> value);
    partial void OnAddress_IdChanged();
    partial void OnCart_IdChanging(System.Nullable<int> value);
    partial void OnCart_IdChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Uname", DbType="NVarChar(50)")]
		public string U_Uname
		{
			get
			{
				return this._U_Uname;
			}
			set
			{
				if ((this._U_Uname != value))
				{
					this.OnU_UnameChanging(value);
					this.SendPropertyChanging();
					this._U_Uname = value;
					this.SendPropertyChanged("U_Uname");
					this.OnU_UnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Pwd", DbType="NVarChar(MAX)")]
		public string U_Pwd
		{
			get
			{
				return this._U_Pwd;
			}
			set
			{
				if ((this._U_Pwd != value))
				{
					this.OnU_PwdChanging(value);
					this.SendPropertyChanging();
					this._U_Pwd = value;
					this.SendPropertyChanged("U_Pwd");
					this.OnU_PwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Email", DbType="NVarChar(MAX)")]
		public string U_Email
		{
			get
			{
				return this._U_Email;
			}
			set
			{
				if ((this._U_Email != value))
				{
					this.OnU_EmailChanging(value);
					this.SendPropertyChanging();
					this._U_Email = value;
					this.SendPropertyChanged("U_Email");
					this.OnU_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Id", DbType="Int")]
		public System.Nullable<int> Address_Id
		{
			get
			{
				return this._Address_Id;
			}
			set
			{
				if ((this._Address_Id != value))
				{
					this.OnAddress_IdChanging(value);
					this.SendPropertyChanging();
					this._Address_Id = value;
					this.SendPropertyChanged("Address_Id");
					this.OnAddress_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cart_Id", DbType="Int")]
		public System.Nullable<int> Cart_Id
		{
			get
			{
				return this._Cart_Id;
			}
			set
			{
				if ((this._Cart_Id != value))
				{
					this.OnCart_IdChanging(value);
					this.SendPropertyChanging();
					this._Cart_Id = value;
					this.SendPropertyChanged("Cart_Id");
					this.OnCart_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
